project:
  type: website
  render:
    - ./*.qmd
  resources: 
    - ./cases/human_melanoma_tcr
    - ./cases/canine_tcr

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: SatTCR
      - href: usage.qmd
        text: Getting started
      # - href: pipeline.qmd
      #   text: Pipeline        
      - text: Examples
        menu:
          - text: Canine TCR
            href: canine_tcr.qmd
          - text: Human melanoma TCR
            href: human_melanoma_tcr.qmd        
      - text: Pre-compiled reports
        menu:
          - text: Canine TCR 
            href: cases/canine_tcr/index.html
          - text: Human melanoma TCR
            href: cases/human_melanoma_tcr/index.html
      # - href: news.qmd
      #   text: News
    right:
    - text: '{{< fa brands github size=2x >}}'
      href: https://github.com/Ong-Research/SatTCR
  search:
    keyboard-shortcut: ["?", "H"]
  page-footer: 
    background: dark
    center: "Copyright (c) 2025 SMPH / Department of Biostatistics and Medical Informatics Ong Lab / UWCCC CISR"
    
navbar:
  structure:
    right: [search, github]

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true



